### ISSUE TITLE
Swift 4 support

### ISSUE THREAD

**Issue by atalayasa** [terutoyamasaki/GoneVisible#1]
Thanks for library it is really useful for my project could you please update for swift 4 ?

**Comment by atalayasa** [comment]
There is no need sorry.

**Comment by freishya** [comment]
My experience one line update to make running well in swift 4
`constraint.priority =751` to `constraint.priority = UILayoutPriority(rawValue: 751)`
thank's for this library

**Comment by snoozelag** [comment]
Thank you for using this library. (^^
