### ISSUE TITLE
cannot import your library(error)

### ISSUE THREAD

**Issue by devEntrega** [terutoyamasaki/GoneVisible#2]
I was trying pod install and then it gives me an error about your library

`[!] Error installing GoneVisible
[!] /usr/bin/git clone https://github.com/snoozelag/GoneVisible.git /var/folders/f5/qnwtrkg16y99d9yxxrwd2f9c0000gn/T/d20180413-14971-169ubyz --template= --single-branch --depth 1 --branch v1.2.0

Cloning into '/var/folders/f5/qnwtrkg16y99d9yxxrwd2f9c0000gn/T/d20180413-14971-169ubyz'...
warning: Could not find remote branch v1.2.0 to clone.
fatal: Remote branch v1.2.0 not found in upstream origin`

**Comment by snoozelag** [comment]
Fixed. I mistakenly made this branch name ```1.2.0``` in this repository. Correctly ```v1.2.0```. I fixed it so it works.

Please try ```pod install``` again.
